### PR TITLE
1.0.0-rc1

### PR DESCRIPTION
**Pull request by aberezkin**
Are we good with that?

### CODE REVIEW

**Comment by aberezkin** [comment]
Once we merge it, I gonna publish new version to npm.

**Comment by UncleDave** [comment]
This looks fine, I think we're good to go (and if we're not, lucky it's a prerelease!).

I've been poking around in my terminal, hopefully the release script will work better this time and here are some special options to use this time around:

`npm run release -- --dry-run --prerelease rc` will let you test the process and check the changelog has the right stuff in it, etc. When you're happy you can use: `npm run release -- --prerelease rc` and it should be tagged `1.0.0-rc.0`

**Comment by UncleDave** [comment]
@aberezkin could you push the changes that the release script should have made to the changelog and package?

**Comment by aberezkin** [comment]
Hmm, looks like something went wrong because my local repo is up to date with the remote.

**Comment by aberezkin** [comment]
@UncleDave the changelog is saved in CHANGELOG.md, though

**Comment by UncleDave** [comment]
You can't push?

**Comment by aberezkin** [comment]
I have nothing to push.

**Comment by aberezkin** [comment]
The CHANGELOG.md on the master branch has everything it should have. I think I should have ran release script on `development` branch.

**Comment by UncleDave** [comment]
No you should have run the release script on master after the merge (as I assume you have done)
What does your `git status` show?

**Comment by aberezkin** [comment]
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```
`release` script has the `git push` command

**Comment by UncleDave** [comment]
Wait, so you have the `1.0.0` changes in your local changelog, but it says there are no changes? I can see that the script pushed the tags but there should be a commit aswell.

**Comment by UncleDave** [comment]
Hold up, no it is there, I think I've been looking at `development` the whole time.

**Pull request merged**
