### PR TITLE
Angular 4.0, error handling, max file size, multiple components

### PR DESCRIPTION
**Pull request by UncleDave**
Service now returns a response object, which includes the status code.
Handle upload errors and emit them through the onFileUploadFinish event.
Updated stylesheet with changes from inline styles.
Updated HTML with changes from inline HTML.
Added some inputs to allow the implementing application to specify a maximum file size.

Use case for error handling change:
My server has a file size limit of 2MB, if a file over this size is posted it will respond with 400 BAD REQUEST, the library should emit the onFileUploadFinish event in this case, and allow the implementing application to handle the error.

This was tested with a fresh @angular/cli 1.0.0 project with @angular 4.0.0

### CODE REVIEW

**Comment by aberezkin** [comment]
Is angular 4 backwards compatible?

**Comment by UncleDave** [comment]
Works for me with Angular 2.4.9 provided the `node_modules/angular2-image-upload/node_modules` folder gets deleted, dunno why it keeps coming back but with Angular 4 it appears to require it (or at least not blow up because of it).

**Comment by aberezkin** [comment]
Okay, gimme some time to test it. Need to look at styles.

By the way, some guy dropped me a line requesting "max size" feature so you hit the spot with this pr.

**Comment by UncleDave** [comment]
Figured out the `node_modules` issue: angular needs to be a peer dependency, the lib doesn't need its own version of angular, it just needs to use whatever the implementing app has.

**Pull request merged**
