### PR TITLE
Support Ahead of Time compilation

### LINKED ISSUE #25: angular-cli 1.0.0.beta.28.3 ImageUploadModule Problem
I use angular-cli for developing angular 2 application.But I have a problem about ImageUploadModule and I know that this problem was sent before.But I did not solve this problem.Please help me about this problem.Thank you

```
ERROR in Error encountered resolving symbol values statically. Calling function 'ImageUploadModule', function calls are not supported. Consider replacing the functio
n or lambda with a reference to an exported function
```

### PR DESCRIPTION
**Pull request by UncleDave**
Resolves #25 #13 

Updated angular, added angular compiler.
Build process uses angular compiler instead of typescript directly.
Check in lib folder as the metadata files are required for AOT compilation.
All instances of private Inputs and Outputs have been changed - this won't work with AOT compilation.
Changed some private properties that were used in the view to public - again required by AOT compiler.
Removed some unused code.

### CODE REVIEW

**Comment by aberezkin** [comment]
HI! Thank you VERY VERY MUCH. So many people are reporting this issue but I to be frank just don't have time for this. Trying to start a business. The one moment that embarrasses me is that you removed `lib` folder from .gitignore. 

Metadata files are generated, aren't they? It's a bad practice to check in generated files, but it's ok to include these to npm package. If these are not generated is there a way to exclude compiled `*.js` files? 

I think we should do something with that.

And one more time THANK YOU so MUCH. I will give you a hug if I ever meet you IRL.

**Comment by UncleDave** [comment]
Sure, you're right, I'm not too familiar with publishing to npm so I was confusing .gitignore and .npmignore, I've put the lib folder back into .gitignore

**Comment by aberezkin** [comment]
Ok thanks, gimme 5 minutes to check if everything is ok.

**Comment by UncleDave** [comment]
Quick observation - the 0.4.0 you just published doesn't seem to contain the metadata files in the lib folder, did you run a build first?

**Comment by aberezkin** [comment]
Oh, thanks. Wait a sec.

**Comment by aberezkin** [comment]
Now it should be ok.

**Comment by salttechno** [comment]
Hello,

I am still facing an issue when I build the app with `ng build --prod`.

Following is the error:
`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/me/Work/internal/node_modules/angular2-image-upload/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/me/Work/internal/node_modules/angular2-image-upload/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/me/Work/internal/node_modules/angular2-image-upload/node_modules/@angular/core/src/di/opaque_token.d.ts`

Am I doing anything wrong?

**Comment by UncleDave** [comment]
What is your version of npm?

Try removing your node_modules and running `npm i` again.

**Comment by salttechno** [comment]
@UncleDave Thanks. Removing old `node_modules` and running `npm i` again solved the issue.

**Comment by jason111neo** [comment]
@salttechno i am still clueless. which node_modules to remove? ng2? or angular2? image-upload. Build error still persist.

**Comment by UncleDave** [comment]
Remove your project's node_modules folder and run npm i.
If this doesn't fix it try npm i -S angular2-image-upload@latest

**Comment by jason111neo** [comment]
i removed node_modules, ran yarn install and typed in exactly the same command and error 
screen shot 2017-03-29 at 6 24 28 pm
Using angular-cli 1.0.0-rc.2 and angular 4.0.0-rc.2 currently

**Comment by jason111neo** [comment]
Still having the same error after follow the steps
1) remove node_modules
2) yarn install
3) sudo npm i -S angular2-image-upload@latest

angular/cli 1.0.0-rc.2
angular 4.0.0-rc.2

**Comment by UncleDave** [comment]
Please show me your package.json

**Comment by jason111neo** [comment]
"dependencies": {
    "angular2-image-upload": "^0.4.1",
}

**Comment by UncleDave** [comment]
I'm looking into this now, it looks like Angular 4 / Angular-cli 1 require things to be built slightly differently.

**Comment by UncleDave** [comment]
I've tested the changes in #30 against `angular 4.0.0-rc.2` and `@angular/cli 1.0.0-rc.2` and it seems to work, so just wait for that pull request to get merged and your problem should be solved.

Note that Angular 4.0.0 is released now, along with @angular/cli 1.0.0 so you may want to bump up your versions.

**Pull request merged**
